name: Deploy to GitHub Pages

on:
  push:
    branches:
      - source

jobs:
  build:
    name: Build Docusaurus
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build website
        run: yarn build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: docusaurus-build
          path: build

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Allows pushing to the `master` branch

    steps:
      - name: Check out `master` branch
        uses: actions/checkout@v4
        with:
          ref: master  # Check out the `master` branch where the site will be deployed

      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: docusaurus-build  # Use the name given in the upload step

      - name: Copy Build Files to Root
        run: |
          rm -rf ./*
          cp -r build/* ./

      - name: Commit and Push to `master`
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Deploy Docusaurus site"
          git push origin master --force
