name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Trigger on pushes to the master branch

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    permissions:
      pages: write     # Allows deployment to GitHub Pages
      id-token: write  # Allows deployment to use ID token

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all branches

      - name: List Files in Master Branch
        run: |
          echo "Listing files in the current directory:"
          ls -R  # List all files to see what’s present

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
