name: Test Pull Request

on:
  pull_request:
    branches:
      - source

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build website
        run: npm run build

      - name: Verify deployment setup
        run: |
          # Here we could run checks to verify deployment readiness without actually deploying.
          # For example, checking the build output exists.
          if [ ! -d "build" ]; then
            echo "Build directory not found. Deployment verification failed." >&2
            exit 1
          fi

      - name: Verify CNAME file for custom domain
        run: |
          echo "Verifying CNAME file..."
          if [ -f "CNAME" ]; then
            echo "CNAME file exists. Content:"
            cat CNAME
          else
            echo "CNAME file does not exist."
          fi
